### PR TITLE
Add build badges to README

### PR DESCRIPTION
**Pull request by ovainola**
Added missing build, coverage and documentation badges to
README.md.

### CODE REVIEW

**Comment by ahojukka5** [comment]
Maybe also license and issues ?

**Comment by ovainola** [comment]
License explained to be GPLv3 in the README.md? I'll add issue number

**Comment by ahojukka5** [comment]
I mean, badges for license and issues, like in JuliaFEM.jl

**Comment by ovainola** [comment]
Added license and issue badges. Also changed the LICENSE file's content to LGPLv3's content

**Pull request merged**
