### PR TITLE
Final deprecation

### LINKED ISSUE #28: MiniballNext
I created the [MiniBallNext](https://github.com/jw3126/MiniBallNext.jl) repository. It is a complete rewrite from scratch of Miniball. Differences are:

* Its implemented based on Gaertners paper, not the C++ implementation. As such I put an MIT license on it.
* The api is different. The input is an iterator of points, the output is a pair `(center, radius)`.
* It is very modular
* In my opinion the implementation is very readable and close to the math, but I am biased here :smile:

It is more numerically stable than current Miniball.jl master, not sure if it is as good as Gaertners latest C++ code. While MiniBallNext is not perfect, I think it is a better foundation for future improvements then current Miniball.jl master. Please take a look and give me feedback @ahojukka5 @ovainola @TeroFrondelius 
If you like it, I will provide a PR.

### PR DESCRIPTION
**Pull request by jw3126**
close #28

### CODE REVIEW

**Review by TeroFrondelius — APPROVED** [review]

**Comment by jw3126** [comment]
I would like to see some test pass on julia 0.6 and see installation fail on julia 0.7.

**Review by TeroFrondelius — APPROVED** [review]

**Comment by jw3126** [comment]
@TeroFrondelius can you tag a new release?

**Comment by TeroFrondelius** [comment]
@jw3126 is this ok: https://github.com/JuliaFEM/Miniball.jl/releases/tag/untagged-5186f59d6f01bf435de5, I think we should increase the minor, because of other new features of this package.

**Comment by jw3126** [comment]
Yes, `v0.2.0` sounds fine.

**Pull request merged**
