### PR TITLE
unit circle test, see #18 for explanation

### PR DESCRIPTION
**Pull request by TeroFrondelius**
Some broken tests to make sure the bug will be properly fixed.

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
@ovainola still interested in fixing these? I have an email of the C++ version fix.

**Comment by TeroFrondelius** [comment]
@jw3126 can you check and merge this pull request?

**Comment by jw3126** [comment]
Will do, right now Cxx segfaults, if I can't fix it I will hack together something using `ccall` just takes some time.

**Comment by jw3126** [comment]
```
Test Summary:      | Pass  Total
broken 5 points 2d |    2      2
Test Summary:      | Pass  Total
broken 6 points 3d |    2      2
Test Summary: | Pass  Broken  Total
fuzz tests    | 3197       3   3200
Test Summary:                  | Pass  Total
unit circle bug failure points |    7      7
Test Summary:              |  Pass  Broken   Total
stastical unit circle test | 99981      19  100000
```

**Pull request merged**
